general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "BitstromWera Nerd Font" }
bold = { family = "BitstromWera Nerd Font" }
italic = { family = "BitstromWera Nerd Font" }
size = 11

[window]
padding.x = 10
padding.y = 10
decorations = "None"

[cursor]
style.shape = "beam"

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" },
{ key = "Space", mods = "Control", action = "ToggleViMode" }
]
